var commonUtil = require('../../../util/common.util.page');
var commonFunction = new commonUtil();
var faultSummary = require('../igf-logfault/fault.summary.page');

var GuaranteeWarranty = function (faultDetails) {
    
    /**
     * Locators for elements used in 'Guarantee Warranty Repair' functionality
     */ 
    
    this.gwYesBtn = element(by.xpath("//ion-radio-group[@formcontrolname='isUnderWarranty']//ion-label[contains(text(),'Yes')]/preceding-sibling::ion-radio"));
    this.gwNoBtn = element(by.xpath("//ion-radio-group[@formcontrolname='isUnderWarranty']//ion-label[contains(text(),'No')]/preceding-sibling::ion-radio"));
    this.gwViewBtn = element(by.xpath("//h3[contains(text(), 'Guarantee / Warranty')]/following-sibling::ion-row//ion-button")); 
    this.firstGWRecord = element(by.xpath("//tbody[@formarrayname='propertyCertificateList']//ion-checkbox[1]"));
    this.gwDetailsCloseBtn = element(by.xpath("//app-property-certificate-modal//ion-button")); 
    this.popupTitle = element(by.css ("ion-title.title-default"));
    this.proceedBtn = element(by.xpath("//ion-button[contains(text(),  'Proceed') and contains(@class, 'submit-button')]"));
    this.faultActionStatus = element(by.css("div.banner > h2.banner-heading")); 
   
    this.responseQuestion = element(by.css("div.question-answer > h6.ng-star-inserted"));
    this.dateTimeTypeList = element(by.xpath("//ion-select[contains(@formcontrolname, 'dateTimeType')]"));
    this.dateTimeType = element(by.xpath("//ion-label[contains(text(), '" + faultDetails.dateTimeType + "')]/following-sibling::ion-radio"));
    this.dateTimeBtn = element(by.xpath("//ion-datetime[contains(@formcontrolname, 'dateTime')]"));
    this.dateTimeDoneBtn = element(by.xpath("//button[contains(text(), 'Done')]"));
    this.nextStepTxt = element(by.xpath("//ion-text[contains(text(), 'Please note')]/.."));
  
    this.faultTitle = element(by.xpath("(//h2[contains(text(), '" + faultDetails.title + "')])[2]")); 
    this.ccCompnay = element(by.xpath("//ion-input[contains(@formcontrolname, 'company')]/input"));
    this.ccName = element(by.xpath("//ion-input[contains(@formcontrolname, 'name')]/input"));
    this.ccTelephone = element(by.xpath("//ion-input[contains(@formcontrolname, 'telephone')]/input"));
    this.ccEmail = element(by.xpath("//ion-input[contains(@formcontrolname, 'email')]/input"));
    this.dateTimeBtnLLContractor = element(by.xpath("//ion-datetime[contains(@formcontrolname, 'estimatedVisitAt')]"));
    this.pastDateErrorLLContractor = element(by.xpath("//ion-label[contains(text(), 'Visit Date')]/../following-sibling::ion-text"));
    this.ccConsentCheckbox = element(by.xpath("//ion-checkbox[contains(@formcontrolname, 'hasContractorConsent')]"));
    this.markJobCompletePopupTitle = element(by.css("ion-title.title-default"));
    this.markJobCompletePopupTxt = element(by.css("app-job-completion-modal > ion-content > form > ion-grid > ion-row > ion-col > h6"));
    this.actionAfterGAFTE = element(by.xpath("//app-close-fault//h3"));
    this.displayedReason = element(by.xpath("//app-close-fault//h5"));
    
    this.completeRepair = function(faultReported){
        let fSummary = new faultSummary(faultReported);
        commonFunction.waitForElementToBeVisible(this.faultTitle, "Fault title");
        commonFunction.scrollToElement(this.gwYesBtn);
        commonFunction.clickOnElement(this.gwYesBtn, 'Guarantee Warrantee Yes button');
        commonFunction.clickOnElement(this.gwViewBtn, "Guarantee Warrantee View button");
        commonFunction.waitForElementToBeVisible(this.gwDetailsCloseBtn);
        commonFunction.clickOnElement(this.firstGWRecord, "First Guarantee Warrantee record");
        commonFunction.clickOnElement(this.gwDetailsCloseBtn, "Guarantee Warrantee Close button");
        commonFunction.scrollToElement(this.proceedBtn);
        commonFunction.clickOnElement(this.proceedBtn, "Proceed button");
        let gwConfirmationMsg = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "Guarantee Warrantee Repair Confirmation Message"); 
        expect(gwConfirmationMsg).toContainData(faultReported.gwRepairConfirmMsg);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Guarantee Warrantee Repair confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");        
        commonFunction.scrollToElement(fSummary.faultStatus);
        let gaeFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after Guarantee Warrantee repair is chosen"); 
        expect(gaeFaultStatus).toContainData(faultReported.faultStatusGAE); 
        commonFunction.scrollToElement(this.faultActionStatus);           
        let gaeFaultAction = commonFunction.updateVerificationObject(this.faultActionStatus, "Fault Action after Guarantee Warrantee repair is chosen"); 
        expect(gaeFaultAction).toContainData(faultReported.faultActionGAE);
        commonFunction.scrollToElement(this.responseQuestion);
        let gaeFaultActionQuestion = commonFunction.updateVerificationObject(this.responseQuestion, "GAE - Question which requires an action"); 
        expect(gaeFaultActionQuestion).toContainData(faultReported.faultActionGAEQuestion); 
        commonFunction.scrollToElement(this.gwViewBtn);
        commonFunction.clickOnElement(this.gwViewBtn, "Guarantee Warrantee View button");
        commonFunction.waitForElementToBeVisible(this.gwDetailsCloseBtn);
        let gwDetailsPopupTitle = commonFunction.updateVerificationObject(this.popupTitle, "Guarantee Warrantee Details popup title"); 
        expect(gwDetailsPopupTitle).toContainData(faultReported.gwDetailsPopupTitle); 
        commonFunction.clickOnElement(this.gwDetailsCloseBtn, "Guarantee Warrantee Details close button");
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseGAE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseGAE), faultReported.positiveResponseGAE);
        commonFunction.waitForElementToBeVisible(this.markJobCompletePopupTxt, "Mark Job Complete popup");
        let jobCompletePopupTitle = commonFunction.updateVerificationObject(this.markJobCompletePopupTitle, "Mark Job Complete popup title"); 
        expect(jobCompletePopupTitle).toContainData(faultReported.markJobCompleteTitle);
        let jobCompletePopupText = commonFunction.updateVerificationObject(this.markJobCompletePopupTxt, "Mark Job Complete popup text"); 
        expect(jobCompletePopupText).toContainData(faultReported.markJobCompleteTxt);
        commonFunction.clickOnElement(this.dateTimeBtn, "Date time picker");
        commonFunction.setDate(faultReported.jobCompleteDateValue);
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button','YES'), "Mark Job Complete popup Yes button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);
        let gwfteFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after job is completed"); 
        expect(gwfteFaultStatus).toContainData(faultReported.faultStatusGAFTE);
        commonFunction.scrollToElement(this.faultActionStatus);
        let gwfteFaultAction = commonFunction.updateVerificationObject(this.faultActionStatus, "Fault Action after job is completed GAFTE"); 
        expect(gwfteFaultAction).toContainData(faultReported.faultActionGAFTE);
        commonFunction.scrollToElement(this.responseQuestion);
        let gwfteFaultActionQuestion = commonFunction.updateVerificationObject(this.responseQuestion, "Question which requires an action GAFTE"); 
        expect(gwfteFaultActionQuestion).toContainData(faultReported.faultActionGAFTEQuestion);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseGAFTE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseGAFTE), faultReported.positiveResponseGAFTE);
        let tenantSatisfyConfirmationMsg = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "Tenant satisfied and fault closure Confirmation Message"); 
        expect(tenantSatisfyConfirmationMsg).toContainData(faultReported.tenantSatisfyConfirmationMsg);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Tenant satisfied and fault closure confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(this.faultActionStatus);
        let gwfteResponseFaultAction = commonFunction.updateVerificationObject(this.faultActionStatus, "Fault Action after tenant is satisfied"); 
        expect(gwfteResponseFaultAction).toContainData(faultReported.faultActionAfterGAFTE);
        let gwfteResponseNextAction = commonFunction.updateVerificationObject(this.actionAfterGAFTE, "Next Action after tenant is satisfied"); 
        expect(gwfteResponseNextAction).toContainData(faultReported.faultNextActionAfterGAFTE);
        commonFunction.scrollToElement(this.displayedReason);
        let closeReasonDisplayed = commonFunction.updateVerificationObject(this.displayedReason, "Fault closure reason"); 
        expect(closeReasonDisplayed).toContainData(faultReported.faultCloseReason);  
        commonFunction.scrollToElement(fSummary.faultStatus);
        let gwfteResponseFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after tenant is satisfied"); 
        expect(gwfteResponseFaultStatus).toContainData(faultReported.faultStatusAfterGAFTE);
    } 

    this.notCompletedRepair = function(faultReported){
        let fSummary = new faultSummary(faultReported);
        commonFunction.waitForElementToBeVisible(this.faultTitle, "Fault title");
        commonFunction.scrollToElement(this.gwYesBtn);
        commonFunction.clickOnElement(this.gwYesBtn, 'Guarantee Warrantee Yes button');
        commonFunction.clickOnElement(this.gwViewBtn, "Guarantee Warrantee View button");
        commonFunction.waitForElementToBeVisible(this.gwDetailsCloseBtn);
        commonFunction.clickOnElement(this.firstGWRecord, "First Guarantee Warrantee record");
        commonFunction.clickOnElement(this.gwDetailsCloseBtn, "Guarantee Warrantee Close button");
        commonFunction.scrollToElement(this.proceedBtn);
        commonFunction.clickOnElement(this.proceedBtn, "Proceed button");
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Guarantee Warrantee Repair confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");        
        commonFunction.scrollToElement(fSummary.faultStatus);
        let gaeFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after Guarantee Warrantee repair is chosen"); 
        expect(gaeFaultStatus).toContainData(faultReported.faultStatusGAE); 
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.negativeResponseGAE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.negativeResponseGAE), faultReported.negativeResponseGAE);
        let repairNotCompleteConfirmationMsg = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "Guarantee Warrantee Repair not completed confirmation message"); 
        expect(repairNotCompleteConfirmationMsg).toContainData(faultReported.repairNotCompleteConfirmMsg);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Guarantee Warrantee Repair not completed confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status"); 
        commonFunction.scrollToElement(fSummary.faultStatus);
        let faultStatusRepairNotComplete = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after repair not completed by Guarantee Warrantee"); 
        expect(faultStatusRepairNotComplete).toContainData(faultReported.faultStatusNegativeGAEResponse); 
        commonFunction.scrollToElement(this.faultActionStatus);
        let gaeResponseFaultAction = commonFunction.updateVerificationObject(this.faultActionStatus, "Fault Action after repair not completed by Guarantee Warrantee"); 
        expect(gaeResponseFaultAction).toContainData(faultReported.faultActionGAEResponse);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.negativeResponseGAE));
        let responseSelectedGAE = commonFunction.updateVerificationObjectByAttrib(commonFunction.getElementByCssContainingText('ion-button', faultReported.negativeResponseGAE), "Submitted Response GAE", "color");
        expect(responseSelectedGAE).toContainData(faultReported.gaeSubmittedResponse);
        commonFunction.scrollToElement(this.nextStepTxt);
        let nextStepText = commonFunction.updateVerificationObject(this.nextStepTxt, "Next Step after repair not completed response - GAE"); 
        expect(nextStepText).toContainData(faultReported.nextStepGAEResponse);       
    } 
    
    this.checkGWDetails = function(faultReported){
        commonFunction.waitForElementToBeVisible(this.faultTitle, "Fault title");
        commonFunction.scrollToElement(this.gwViewBtn);
        commonFunction.clickOnElement(this.gwViewBtn, "Guarantee Warrantee View button");
        commonFunction.checkOptionData('tbody[formarrayname="propertyCertificateList"] > tr > td', faultReported.gwColumns, faultReported.gwRowData, true, "GW Table");
        commonFunction.clickOnElement(this.firstGWRecord, "First Guarantee Warrantee record");
        commonFunction.checkOptionData('ion-grid.details-section ion-col', faultReported.gwFields, faultReported.gwDetails, true, "GW Details");
        commonFunction.clickOnElement(this.gwDetailsCloseBtn, "gw Details Close button");
    }    
     
    this.changeRepairToLLOwnRepair = function(faultReported){
        let fSummary = new faultSummary(faultReported);
        commonFunction.waitForElementToBeVisible(this.faultTitle, "Fault title");
        commonFunction.scrollToElement(this.gwYesBtn);
        commonFunction.clickOnElement(this.gwYesBtn, 'Guarantee Warrantee Yes button');
        commonFunction.clickOnElement(this.gwViewBtn, "Guarantee Warrantee View button");
        commonFunction.waitForElementToBeVisible(this.gwDetailsCloseBtn);
        commonFunction.clickOnElement(this.firstGWRecord, "First Guarantee Warrantee record");
        commonFunction.clickOnElement(this.gwDetailsCloseBtn, "Guarantee Warrantee Close button");
        commonFunction.scrollToElement(this.proceedBtn);
        commonFunction.clickOnElement(this.proceedBtn, "Proceed button");
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Guarantee Warrantee Repair confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");        
        commonFunction.scrollToElement(fSummary.faultStatus);
        let gaeFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after Guarantee Warrantee repair is chosen"); 
        expect(gaeFaultStatus).toContainData(faultReported.faultStatusGAE);        
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('h6','Want to proceed in a different way?'));
        commonFunction.checkVisibleData('ion-button', faultReported.differentWayOptions, true, "Different way repair option is");
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button',faultReported.differentRepair));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button',faultReported.differentRepair), faultReported.differentRepair);
        commonFunction.scrollToElement(this.proceedBtn);
        commonFunction.clickOnElement(this.proceedBtn, "Proceed button");
        let diffRepairConfirmMsg1 = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "Different Repair Confirmation Message"); 
        expect(diffRepairConfirmMsg1).toContainData(faultReported.diffRepairConfirmationMsg1);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Different repair confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);
        let cliFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after reaching to CLI stage"); 
        expect(cliFaultStatus).toContainData(faultReported.cliUpdatedStatus); 
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.checkVisibleData('ion-button', faultReported.cliOptions, true, "CLI repair option is");
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.cliAction));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.cliAction), faultReported.cliAction);
        commonFunction.scrollToElement(this.proceedBtn);
        commonFunction.clickOnElement(this.proceedBtn, "Proceed button");
        let llRepairConfirmationMsg1 = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "LL Own Repair Confirmation Message1"); 
        expect(llRepairConfirmationMsg1).toContainData(faultReported.cliOwnRepairConfirmMsg1);
        let llRepairConfirmationMsg2 = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "LL Own Repair Confirmation Message2"); 
        expect(llRepairConfirmationMsg2).toContainData(faultReported.cliOwnRepairConfirmMsg2);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Proceed to LL Own Repair confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);      
        let lrleFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after selecting CLI action LL Own Repair"); 
        expect(lrleFaultStatus).toContainData(faultReported.faultStatusLRLE);
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.scrollToElement(this.responseQuestion);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLRLE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLRLE), faultReported.positiveResponseLRLE);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Work In Progress confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);
        let lrleResponseFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after landlord response to LRLE"); 
        expect(lrleResponseFaultStatus).toContainData(faultReported.faultStatusAfterLRLE);
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLRLE));
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', "Add Contractor Details"));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button',  "Add Contractor Details"),  "Add Contractor Details button");
        commonFunction.waitForElementToBeVisible(this.ccCompnay, "Add Contractor Details popup");
        commonFunction.sendKeysInto(this.ccCompnay, faultReported.ccCompany);
        commonFunction.sendKeysInto(this.ccName, faultReported.ccName);
        let rNo1 = Math.floor((Math.random() * 100000) + 1);
        let rNo2 = Math.floor((Math.random() * 10000) + 1);
        let telephone = parseInt(faultReported.ccTelephone, 10);
        commonFunction.sendKeysInto(this.ccTelephone, (telephone + rNo1 + rNo2).toString());
        commonFunction.clickOnElement(this.dateTimeTypeList, "Date/Time Type list");
        commonFunction.clickOnElement(this.dateTimeType, "Date/Time Type option");
        commonFunction.clickOnElement(this.dateTimeBtnLLContractor, "Date/Time Picker");
        commonFunction.setDate(faultReported.visitDateValue);
        commonFunction.scrollToElement(this.ccConsentCheckbox);
        commonFunction.clickOnElement(this.ccConsentCheckbox, "Contractor consent checkbox");
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button',  "SAVE"),  "SAVE button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);
        let lcleFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after visit time scheduled"); 
        expect(lcleFaultStatus).toContainData(faultReported.faultStatusLCLE);
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.scrollToElement(this.responseQuestion);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLCLE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLCLE), faultReported.positiveResponseLCLE);
        commonFunction.waitForElementToBeVisible(this.markJobCompletePopupTxt, "Mark Job Complete popup");
        let jobCompletePopupText = commonFunction.updateVerificationObject(this.markJobCompletePopupTxt, "Mark Job Complete popup text"); 
        expect(jobCompletePopupText).toContainData(faultReported.markJobCompleteTxt);
        commonFunction.clickOnElement(this.dateTimeBtn, "Date time picker");
        commonFunction.setDate(faultReported.jobCompleteDateValue);
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button','YES'), "Mark Job Complete popup Yes button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(fSummary.faultStatus);
        let lfteFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after job is completed"); 
        expect(lfteFaultStatus).toContainData(faultReported.faultStatusLFTE);
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.scrollToElement(this.responseQuestion);
        commonFunction.scrollToElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLFTE));
        commonFunction.clickOnElement(commonFunction.getElementByCssContainingText('ion-button', faultReported.positiveResponseLFTE), faultReported.positiveResponseLFTE);
        let tenantSatisfyConfirmationMsg = commonFunction.updateVerificationObject(fSummary.confirmationMessage, "Tenant satisfied and fault closure Confirmation Message"); 
        expect(tenantSatisfyConfirmationMsg).toContainData(faultReported.tenantSatisfyConfirmationMsg);
        commonFunction.clickOnElement(fSummary.confirmationOKBtn, "Tenant satisfied and fault closure confirmation OK button");
        commonFunction.waitForElementToBeVisible(this.faultActionStatus, "Fault action status");
        commonFunction.scrollToElement(this.faultActionStatus);
        commonFunction.scrollToElement(this.displayedReason);
        let closeReasonDisplayed = commonFunction.updateVerificationObject(this.displayedReason, "Fault closure reason"); 
        expect(closeReasonDisplayed).toContainData(faultReported.faultCloseReason);  
        commonFunction.scrollToElement(fSummary.faultStatus);
        let lfteResponseFaultStatus = commonFunction.updateVerificationObject(fSummary.faultStatus, "Fault Status after tenant is satisfied"); 
        expect(lfteResponseFaultStatus).toContainData(faultReported.faultStatusAfterLFTE);
    }
}
module.exports = GuaranteeWarranty;
